#!/usr/bin/env bash
set -e

read -p "Issue title: " title

output=$(gh issue create --title "$title" --body "" | tail -n 1)

pattern='https://.*/issues/([0-9]+)'
if [[ "$output" =~ $pattern ]]; then
    issue_number=${BASH_REMATCH[1]} 
    echo "Issue number is: $issue_number"
else    
    echo "Could not get issue number, output:"
    echo $output
    exit 1
fi

branch_title=$(echo $title | sed -E 's/([.~^:?*\[@{}<>|\\"''()`,]|[\]]|[[:space:]])+/_/g')

git switch --create "issue-${issue_number}-${branch_title}"
